version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: atm_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=atm_db
      - JWT_SECRET=supersecretjwtkey_12345
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - atm_network

  mysql_db:
    image: mysql:8.0
    container_name: atm_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: atm_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - atm_network

networks:
  atm_network:
    driver: bridge

volumes:
  db_data:
